#! /bin/sh
arg1=`wslpath -a $1`

cd $arg1
# backing up old config.h.in
if [ -f "./config.h.in" ];then
    echo "backing up old config.h.in to config.h.in.old"
    rm -f ./bak/config.h.in.old
    mv ./config.h.in ./bak/config.h.in.old
    
#else
    #echo "文件不存在"
    
fi
/usr/bin/autoheader
returnvalue=$?
echo "autoheader return: $returnvalue"
if [ $returnvalue -ne 0 ]; then
    echo "autoheader failed"
    if [ -f "./bak/config.h.in.old" ];then
        echo "恢复以前的文件"
        mv ./bak/config.h.in.old  ./config.h.in
        exit 1
    fi
else
    echo "autoheader succeed"
    #mv config.h.in config.h.in
fi
exit 0