#! /bin/sh

arg1=`wslpath -a $1`

cd $arg1
/usr/bin/aclocal
returnvalue=$?
if [ $returnvalue -ne 0 ]; then echo -e "\033[31m aclocal failed \033[0m"; exit 1; else echo -e "\033[32m aclocal succeed \033[0m"; fi
