#! /bin/sh
arg1=`wslpath -a $1`
cd $arg1

if [ -f "./NEWS" ];then
    :
else
    echo "NEWS" >./NEWS
    
fi
if [ -f "./README" ];then
    :
else
    echo "README" >./README
    
fi
if [ -f "./AUTHORS" ];then
    :
else
    echo "AUTHORS" >./AUTHORS
    
fi
if [ -f "./ChangeLog" ];then
    :
else
    echo "ChangeLog" >./ChangeLog
    
fi

/usr/bin/automake --add-missing
returnvalue=$?
if [ $returnvalue -ne 0 ]; then echo " automake failed "; exit 1; else echo " automake succeed "; fi