#! /bin/sh
arg1=$1
arg2=`wslpath -a $2`
cd $arg2
echo "---------------inti start for makefile--------------------"
$arg1/gccautoscan  $2
returnvalue=$?
if [ $returnvalue -ne 0 ]; then echo " gccautoscan failed "; exit 1; fi

$arg1/gccautoheader  $2
returnvalue=$?
if [ $returnvalue -ne 0 ]; then echo " gccautoheader failed "; exit 1; fi

$arg1/gccaclocal  $2
returnvalue=$?
if [ $returnvalue -ne 0 ]; then echo " gccaclocal failed "; exit 1; fi

$arg1/gccautoconf  $2
returnvalue=$?
if [ $returnvalue -ne 0 ]; then echo " gccautoconf failed "; exit 1; fi

$arg1/gccautomake  $2
returnvalue=$?
if [ $returnvalue -ne 0 ]; then echo " gccautomake failed "; exit 1; fi

echo "---------------- inti end for makefile -------------------"